### ISSUE TITLE
Can I set query time?

### ISSUE THREAD

**Issue by Shaun2016** [vesoft-inc/github-statistics#56]
![image](https://user-images.githubusercontent.com/17938959/172842675-9aa1737d-8c70-4316-baa5-7b63197413ba.png)
Hi，i want to statistic pr number, commit number in last year, but i found the default time scope is nearlest year

Can i set query time ?

**Comment by wey-gu** [comment]
It seems to fetch more than one year rather than "the nearest year", actually, it's fetching from the creation time of the repo here

<img width="1861" alt="Screen Shot 2022-06-09 at 8 34 48 PM" src="https://user-images.githubusercontent.com/1651790/172848210-05ee621f-5474-4e0f-be85-44025edffc68.png">
:

**Comment by QingZ11** [comment]
@Shaun2016 hi, I have noticed that the issue you created hasn’t been updated for nearly a month, is this issue been resolved? If not resolved, can you provide some more information? If solved, can you close this issue?

Thanks a lot for your contribution anyway 😊
